### ISSUE TITLE
在windows下，可以指定shell来做diff

### ISSUE THREAD

**Issue by tzws** [ZSaberLv0/ZFVimDirDiff#10]
我把vim的shell设置成了git-bash带的bash，diff 就失败了。

    if filereadable("C:/git-sdk-64/usr/bin/bash.exe")
        let &shell='C:/git-sdk-64/usr/bin/bash.exe'
        let &shellcmdflag="--login -c"
        let &shellxquote="\""
        let $CHERE_INVOKING=1
        set shellslash
    endif
这种情况下，其实是用 bash 去执行了cmd.exe 的命令了。

假如我想在gvim里启动shell，用git-bash带的bash，这个功能更强；在做文件夹diff的时候，用cmd.exe 来执行，cmd.exe 启动更快。git-bash/cygwin bash 启动一下，要好几秒。

**Comment by ZSaberLv0** [comment]
加了些配置, 参见 FAQ, 这样子应该可行

```
let g:ZFDirDiffLangString = 'LANG= '
function! ZF_DirDiffTempname()
    return '/tmp/.ZFDirDiffCache'
endfunction
```
