### ISSUE TITLE
可以增加一个参数，或者一组快捷键，过滤空文件吗？

### ISSUE THREAD

**Issue by tzws** [ZSaberLv0/ZFVimDirDiff#11]
有时候有很多空文件，光有个文件名，但是是0byte。这样的文件没啥意义。如果有一组快捷键可以不展示空文件，就好了。

这是Beyond Compare 也没有的功能。

**Comment by ZSaberLv0** [comment]
`diff` 并没有提供这样的功能, 加个这样的选项需要每次额外的遍历读取所有文件, 感觉得不偿失

你真需要的话, 我添加了个 `ZFDirDiffCustomFilter(path, type)` 可以进行自定义过滤
