### ISSUE TITLE
CursorLine highlighting is changed in dirdiff and isn't restored when leaving

### ISSUE THREAD

**Issue by idbrii** [ZSaberLv0/ZFVimDirDiff#15]
I use full height CursorLine (I think I'm just using the default color because it's not defined in my colorscheme). When I open ZFDirDiff, the CursorLine changes to underline instead (looks like I can g:ZFDirDiffHLFunc_addHL to customize). When I leave ZFDirDiff, it's not restored.

Minimal repro:

```vim

let s:plugins = ['sensible']
let s:plugins += ['zfvimdirdiff']

set runtimepath-=~/.vim
set runtimepath-=~/.vim/after
set runtimepath-=~/vimfiles
set runtimepath-=~/vimfiles/after
for plugin in s:plugins
    exec "set runtimepath^=~/.vim/bundle/". plugin
    exec "set runtimepath+=~/.vim/bundle/". plugin ."/after"
endfor
set viminfofile=NONE

set cursorline
colorscheme desert

command! Test ZFDirDiff ~/.vim/colors ~/.vim/plugin
```

```
$ mvim -Nu ~/.vim/reprovimrc.vim -U NONE ~/.vim/reprovimrc.vim 
" navigate up and down to see full height cursorline. Then:
Test
" navigate up and down to see underline cursorline. Then:
tabclose
" navigate up and down to see underline cursorline instead of full height one.
```

**Comment by idbrii** [comment]
I previously used will133/DirDiff and assumed because ZFVimDirDiff doesn't have a quit command, it doesn't require special quitting procedure. Looking into the code more, I see that `q` is mapped to a quit function and using that function successfully restores the highlight.

However, ZF_DirDiffHL_CursorLine_augroup seems to be defined to catch any other ways the user might exit. But since s:setupDiffBuffer() uses `bufhidden=hide` instead of  `bufhidden=delete`, it doesn't work. Using `bufhidden=delete` might be a bit weird if dirdiff gets torn down and the other buffer is closed.

In theory, the TabClosed autocmd should help, but I can't figure out how to make it work in this case:

```
    let bufnr = bufnr()
    augroup ZFDirDiff
        au! * <buffer>
        exec "autocmd TabClosed <buffer> exec ".. bufnr .."bdelete"
    augroup END
```

**Comment by idbrii** [comment]
For reference, this is the customization required to prevent any CursorLine changes:

```vimscript
let g:ZFDirDiffUI_headerTextFunc = 'David_DirDiff_headerText'
```

**Comment by ZSaberLv0** [comment]
> But since s:setupDiffBuffer() uses `bufhidden=hide` instead of `bufhidden=delete`, it doesn't work. Using `bufhidden=delete` might be a bit weird if dirdiff gets torn down and the other buffer is closed.

the `bufhidden=hide` was copied from other code, I did not noticed that

changing to `delete` seems to solve this issue, but what's the mean of `a bit weird if dirdiff gets torn down and the other buffer is closed`? I tested for some cases, seems no other side effect

**Comment by idbrii** [comment]
I expected that you'd close all dirdiff buffers since without both of them, they're not longer functional. That's not what currently happens. 

I did have weirdness:

* navigating away from a dirdiff buffer (`gf`) means I cannot navigate back (`:e#`) because it's deleted
* the dirdiff highlighting was still applied to the window (top few lines were red like the header)

I guess you could just clear the buffers and remove all highlighting so if either is still displayed, they're "exited". Doesn't resolve the first one, but maybe that's okay?

Aside: Why does zfdirdiff change CursorLine highlight style? Since it doesn't enable `cursorline`, many people won't see it. The underline doesn't seem more functional than whatever style the user is accustomed to.

**Comment by ZSaberLv0** [comment]
I now understand the case, it's because the default highlight using `matchadd()` was applied to window instead of buffer, maybe we can reset it when `BufHidden`, I have add some commits to solve this issue, please test

---

as for `cursorline`: it's my mistake forgot to `set cursorline`

as for why change CursorLine highlight: I think `UNDERLINE` would be better because it won't disturb diff highlight, especially for 8 bit colorschemes

to bypass this, you may change highlight impl to `ZF_DirDiffHL_resetHL_matchadd` and `ZF_DirDiffHL_addHL_matchadd`

**Comment by idbrii** [comment]
>I think UNDERLINE would be better because it won't disturb diff highlight, especially for 8 bit colorschemes

Wouldn't those colorschemes already apply a color that looks good? I'd expect 8-bit colorschemes should already be using underline if nonunderline looks bad. Unless you mean that too many of them don't consider that case and you'd rather have zfdirdiff handle it than expect the colorschemes to smarten up?

----

I haven't had a chance to check your new commits yet.
