### ISSUE TITLE
Suggestion: use Normal for  ZFDirDiffHL_Same 

### ISSUE THREAD

**Issue by idbrii** [ZSaberLv0/ZFVimDirDiff#16]
I found the diff highlighting colors confusing at first because it lacked the familiar red of my diff colors and it had an unfamiliar yellow from my folding. I don't think it makes sense to add red (unless you separated the colors between left and right so only on left was removed red and only on right was added green). But what do you think about de-emphasizing files that are the same just like you diffs are displayed?

```
" change this:
highlight link ZFDirDiffHL_Same Folded
" to this:
highlight link ZFDirDiffHL_Same Normal
```

Users can always add that line to `~/.vim/after/plugin/zfdirdiff.vim` with the same result, but I thought it would make sense to be the default behaviour. I tested several colorschemes (jellybeans, moira, lucius, navajo-night) and only one made Folded look less eye-catching than Normal.

**Comment by ZSaberLv0** [comment]
low contrast colorschemes may have `Normal` less eye-catching than `Folded`, but others not, for my experiences, `Folded` seems better for more case, typical samples: gruvbox, molokai, onedark

a possible better solution may be, use `Folded`'s foreground, and use `NONE` as background, but I can't find a simple and effective way to achieve this

**Comment by idbrii** [comment]
Okay. It's easy enough for users to configure and this issue will help them figure out how to do that.

Good enough for me. Thanks for the great plugin!
