### ISSUE TITLE
diff dir 页签增加自动刷新快捷键

### ISSUE THREAD

**Issue by lymslive** [ZSaberLv0/ZFVimDirDiff#2]
发现有时候从 diff file 回到 diff dir 页签时，刚同步完的两个文件高亮没有变化。
下意识就想到有没有刷新功能。
这在有外部程序更改了文件夹内容时也可能有用的。

**Comment by ZSaberLv0** [comment]
用 `q` 退出 diff file 的时候应该是有自动刷新的, 其他方式要加各种 autocmd 不方便弄 (懒)

另外, 可以用 `g:ZFDirDiffKeymap_update` 指定刷新的快捷键, 默认是 `DD`
