### ISSUE TITLE
Doesn't create intermediate folders with doing "sync here"

### ISSUE THREAD

**Issue by idbrii** [ZSaberLv0/ZFVimDirDiff#21]
Steps:

```
mkdir -p hi/there/folder hi/unwanted ha
touch hi/there/folder/file hi/unwanted/file
gvim .
:DirDiff hi ha
/folder
dp
```

Nothing happens.

I'd expect directory 'there' to be created when I'm trying to sync (ZF_DirDiffSyncToThere). Instead, I have to copy each parent folder (using Yes instead of All to avoid getting directory 'unwanted'). Once the parent folders exist, I can use `dp` to copy the file.

Am I doing something wrong?

**Comment by ZSaberLv0** [comment]
thanks for report
`diff` only report one depth items for dir only type, so I used `globpath()` to search sub files for displaying, the issue was caused around there

**Comment by idbrii** [comment]
Looks good. Thanks!
