### ISSUE TITLE
`highlight link ZFDirDiffHL_Same Normal` doesn't change highlight

### ISSUE THREAD

**Issue by idbrii** [ZSaberLv0/ZFVimDirDiff#26]
**Describe the bug:**

Using `highlight link ZFDirDiffHL_Same Normal` in vimrc or ~/.vim/after/plugin/zfdirdiff.vim doesn't change highlight.

**To reproduce:**

1. create `reprovimrc.vim`:

```vim
" Invoke with:
" gvim -Nu ~/.vim/reprovimrc.vim -U NONE +"ZFDirDiff ~/.vim/bundle/zfdirdiff/test/left/ ~/.vim/bundle/zfdirdiff/test/right/"

" all plugins should work with sensible as a baseline.
let s:plugins = ['sensible']
let s:plugins += ['zfdirdiff']

set runtimepath-=~/.vim
set runtimepath-=~/.vim/after
set runtimepath-=~/vimfiles
set runtimepath-=~/vimfiles/after
for plugin in s:plugins
    exec "set runtimepath^=~/.vim/bundle/". plugin
    exec "set runtimepath+=~/.vim/bundle/". plugin ."/after"
endfor
set viminfofile=NONE

colorscheme desert

" This doesn't work -- what README says to do.
highlight link ZFDirDiffHL_Same Normal
" This works
"~ highlight default link ZFDirDiffHL_Same Normal
```

1. start with `gvim -Nu ~/.vim/reprovimrc.vim -U NONE +"ZFDirDiff ~/.vim/bundle/zfdirdiff/test/left/ ~/.vim/bundle/zfdirdiff/test/right/"`
1. copy b.txt to the other side
2. observe that b.txt is highlighted with Fold (orange text) instead of Normal (white text)
3. Do `:highlight link ZFDirDiffHL_Same Normal` and b.txt now looks as expected

I tried moving the highlight commands from ZFVimDirDiff.vim to a new syntax/ZFDirDiffRight.vim (and Left), but then neither command worked from my vimrc.

My read of the docs is that you're doing the right thing, so is this a vim bug? 

**Environment:**

* vim version : 8.2.2497 x64
* OS : win10 x64

**Comment by ZSaberLv0** [comment]
can not reproduce with your config, with these envs:

* MacOS's vim 8.2 (included patches: 1-2100)
* Windows' gVim 8.2

the only difference should be the `sensible` plugin and the vim versions,
~~I'll try a updated vim when able~~ (8.2.2500 seems alright, too)

---

and here's my minimal config, work as expect, too

``` vim
filetype plugin on
syntax on
set nocompatible
let g:plug_home = $HOME . '/.vim/bundle'
let g:plug_url_format = 'https://github.com/%s'
execute 'source ' . g:plug_home . '/vim-plug/plug.vim'
silent! call plug#begin()
Plug 'junegunn/vim-plug'
Plug 'ZSaberLv0/ZFVimDirDiff'
highlight link ZFDirDiffHL_Same Error
call plug#end()
```

**Comment by idbrii** [comment]
Hm. With my reprovimrc I see the behaviour on macvim 8.2.1710 (on both gui and terminal).

To run your config, I used it as my .vimrc and removed my ~/.vim/ and then I get this:
<img width="394" alt="Screen Shot 2021-02-18 at 4 56 14 PM" src="https://user-images.githubusercontent.com/43559/108441584-4488fd80-720a-11eb-9218-e609402b2b19.png">

b.txt is the same in both (I used `dp` to copy from right to left). It should be using Same, which is defined as Error (red bg) in your minimal. But instead it's using something white.

When that window is open, I can do `:highlight link ZFDirDiffHL_Same Error` and the highlighting changes:

<img width="394" alt="Screen Shot 2021-02-18 at 4 56 29 PM" src="https://user-images.githubusercontent.com/43559/108441590-49e64800-720a-11eb-8559-f01ed8152487.png">

So clearly it's not using the highlighting specified in the vimrc.

You're seeing red background on files that are the same without any other changes?

**Comment by ZSaberLv0** [comment]
> You're seeing red background on files that are the same without any other changes?

yes, just use my minimal config mentioned above, and `vim -Nu min.vim -U NONE +"ZFDirDiff ~/.vim/bundle/zfdirdiff/test/left/ ~/.vim/bundle/zfdirdiff/test/right/"`, no other steps
on both `dir_same/a.txt` and `b.txt` copied as your mentioned, nothing wrong, highlighted as `Error` as expected
![image](https://user-images.githubusercontent.com/6846867/108455828-f0355a80-72a9-11eb-82d1-d69316506c7c.png)
![image](https://user-images.githubusercontent.com/6846867/108455847-f88d9580-72a9-11eb-9be5-f6e8c59497a1.png)

---

the highlight logic has nothing special, just simply `highlight default link XXX` and `matchadd()`, all highlight code is straightforward without any tricks, maybe it's vim's issue?

**Comment by ZSaberLv0** [comment]
> You're seeing red background on files that are the same without any other changes?

yes, with my minimal config mentioned above, and `vim -Nu min.vim -U NONE +"ZFDirDiff ~/.vim/bundle/ZFVimDirDiff/test/left ~/.vim/bundle/ZFVimDirDiff/test/right"` as your steps, no other steps
both the `dir_same/a.txt` and `b.txt` highlighted as `Error` as expected
![image](https://user-images.githubusercontent.com/6846867/108459588-e7488700-72b1-11eb-9e6c-aa39b9c9aa62.png)

---

the highlight logic has nothing special, just `highlight default link XXX` and `matchadd()`, all code is straightforward without any tricks, maybe it's vim's issue?

**Comment by ZSaberLv0** [comment]
https://github.com/ZSaberLv0/ZFVimDirDiff/commit/7610fc4a42f3dbc012c772e633b80eecd48a805f
the highligh logic has been completely rewrite because of the new async version, have it a try?
