### ISSUE TITLE
和ctags插件冲突

### ISSUE THREAD

**Issue by leoatchina** [ZSaberLv0/ZFVimDirDiff#27]
在安装了这个插件后，会导致 韦大的 vim-quickui/vim-preview不能正常工作 ， 报不能找到 相应tags的错误 
vim-gutentags也失效，但是我看生成的tags文件，内容是正常的。
在centos  untun20.04, windows， 以及 U-ctags,  e-ctags都会出现这个问题
部分情况下连`c-]`都会出错，不能跳转、preview

**Comment by ZSaberLv0** [comment]
无法复现, 能否提供个最简配置复现?

另, 看这现象像是某些文件被 `wildignore` 忽略了, 是否装了 ZFVimIgnore? 默认会忽略一些常见的文件夹, 可能意外被忽略了?

**Comment by leoatchina** [comment]
确定是 ZFVimIgnore的问题，可能是把.LfCache文件夹给ignore了而我的tags是放在这个文件夹下面
此插件我还没有深入研究过，过段时间有空了研究下怎么和我用的主力插件兼容。

**Comment by leoatchina** [comment]
此插件没有问题，close this issue

**Comment by ZSaberLv0** [comment]
默认会自动识别当前目录和所有父目录的 `.gitignore`, 看看是不是被这个忽略了?

可以加个配置忽略部分 ignore 规则:

``` vim
function! s:myFilter(ignore)
    let i = len(a:ignore['dir']) - 1
    while i >= 0
        if a:ignore['dir'][i] == '.LfCache'
            call add(a:ignore['dir_filtered'], remove(a:ignore['dir'], i))
        endif
        let i -= 1
    endwhile
endfunction

if !exists('g:ZFIgnoreFilter')
    let g:ZFIgnoreFilter = {}
endif
let g:ZFIgnoreFilter['yourModuleName'] = function('s:myFilter')
```
