### ISSUE TITLE
Just checking, is this file needed?

### ISSUE THREAD

**Issue by qpkorr** [ZSaberLv0/ZFVimDirDiff#29]
[This file](https://github.com/ZSaberLv0/ZFVimDirDiff/blob/master/test/left/p0/p1/%E7%9A%84.txt) 
Hi,
Thanks for the great plugin - just wondering - is the above file needed?
It empty, and I suspect my system isn't set up to handle unicode as well as it needs to be to work with this file - I just wondered if it's meant to be there given no other files in the repository seem to have unicode filenames?
Thanks,
John

**Comment by ZSaberLv0** [comment]
it's just for test
if it won't cause troubles, just leave it there
if it would, tell me and I will remove it

**Comment by qpkorr** [comment]
The name of it is causing me troubles - it comes up as test/left/p0/p1/347232204.txt on my system - clearly it's not understanding unicode properly.If you could rename it, or remove it, I'd be very grateful as it's the only file I encounter that causes me such problems.Thank you!
    On Thursday, March 3, 2022, 01:24:26 PM GMT+11, ZERO ***@***.***> wrote:  
 
 


it's just for test
if it won't cause troubles, just leave it there
if it would, tell me and I will remove it

—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by qpkorr** [comment]
Thank you!
