### ISSUE TITLE
对比文件夹时，复制文件后报一堆错误

### ISSUE THREAD

**Issue by lymslive** [ZSaberLv0/ZFVimDirDiff#3]
Hi, 我又来用你的工具了。
对比目录窗口下，我使用 dp 命令后从一边复制（缺失的）文件到另一边，然后报一堆错误，
b:isLeft 未定义
然后目录对比的标签页被关闭
但文件是复制成功的，重新对比目录时能发现

**Comment by ZSaberLv0** [comment]
啊哈哈, 脑抽写了个 `while winnr('$') > 0` 死循环, 已处理, 更新一下
