### ISSUE TITLE
Is it possible to remove ZF prefix?f

### ISSUE THREAD

**Issue by albfan** [ZSaberLv0/ZFVimDirDiff#34]
Thanks a lot for creating this plugin, works exactly as expected, but why all the ZF prefix?

for diff two dirs I just expect to provide a `DirDiff` command.

Is it possible to work on that?

By now I solve it using:

    command! -nargs=+ -complete=file DirDiff :call ZFDirDiff(<f-args>)

**Comment by ZSaberLv0** [comment]
that's a personal prefix make it never conflict with other plugins, as you mentioned, you may alias to any other command name or keymap you prefer

---

if you interested in what `ZF` is, it originally stands for `Zero Framework`, main thoughts inherits from [ZFFramework](https://github.com/ZFFramework/ZFFramework): reduce any "external dependencies" ("external" means anything other than "source code" itself), including build tool chain or runtime mechanism, and only use when really necessary

**Comment by albfan** [comment]
Ok. Just if at some point you think this is interesting I can provide solutions.

For me that custom command solve it
