### ISSUE TITLE
needs redraw! after any action

### ISSUE THREAD

**Issue by albfan** [ZSaberLv0/ZFVimDirDiff#36]
I think there's a TODO on README about this.

just triggering :redraw! after each task is enough to view all buffers again

I can work on this, if there's no better workaround

**Comment by ZSaberLv0** [comment]
could you supply reproduce steps and screenshots?

**Comment by albfan** [comment]
Sure. Let me collect it and show. I can even add a tentative PR with my workaround

**Comment by albfan** [comment]
Here, just comparing two maven projects, so I wantto remove the targets dir (build directory)

https://user-images.githubusercontent.com/220968/223145367-c96b6e92-60d7-49ee-a2b1-08700f13c973.mp4

using vim 9.0

**Comment by albfan** [comment]
This fixes it for me:

```
diff --git i/plugin/api.vim w/plugin/api.vim
index 4ba9d3c..8e59fef 100644
--- i/plugin/api.vim
+++ w/plugin/api.vim
@@ -266,6 +266,7 @@ function! ZFDirDiffAPI_update(taskData, ...)
         return
     endif
     call ZFDirDiffAPIImpl_job_update(a:taskData, get(a:, 1, {}))
+    redraw!
 endfunction
 
 " save state which would automatically restored during ZFDirDiffAPI_dataChanged
```

**Comment by ZSaberLv0** [comment]
seems better to place here, and seems no need for `!`

```
diff --git a/plugin/api.vim b/plugin/api.vim
index 4ba9d3c..fe3a6c0 100644
--- a/plugin/api.vim
+++ b/plugin/api.vim
@@ -400,6 +400,7 @@ function! ZFDirDiffAPI_dataChangedImmediately(taskData)

     let Fn_cbDataChanged = a:taskData['option']['cbDataChanged']
     call Fn_cbDataChanged()
+    redraw
 endfunction
 function! s:dataChanged_openStateRestore(taskData)
     if empty(get(a:taskData, 'openState', {}))
```

**Comment by albfan** [comment]
let's review then on PR, will remove my text to avoid noise
