### ISSUE TITLE
文件夹可以折叠/展开吗？

### ISSUE THREAD

**Issue by tzws** [ZSaberLv0/ZFVimDirDiff#4]
类似在Beyond Compare那样。文件夹可以展开、折叠。

**Comment by ZSaberLv0** [comment]
可以用 `set foldmethod=indent`

比如: `autocmd User ZFDirDiff_BufferEnter set foldmethod=indent`

**Comment by tzws** [comment]
已经试过这样了，效果不好。两个文件夹，如果左边有的文件，右边没有，折叠之后就乱了。

        let g:ZFDirDiffFileExclude = '.git,node_modules,*/node_modules/*'
        autocmd FileType ZFDirDiffLeft setlocal foldmethod=indent
        autocmd FileType ZFDirDiffRight setlocal foldmethod=indent

**Comment by ZSaberLv0** [comment]
还真没想到这茬, 我一般用 indent 做光标跳转

可以先试试 `let g:ZFDirDiffShowSameFile = 0`, 有空我看看怎么弄

**Comment by ZSaberLv0** [comment]
已添加, 可以用 `o` `O` `x` `X` 开关文件夹了
