### ISSUE TITLE
Doesn't seem to work

### ISSUE THREAD

**Issue by eyalk11** [ZSaberLv0/ZFVimDirDiff#40]
I have two folders that some files are different.
The output is meaningless. Doesn't show sub directory files, I don't see which is different.
uris are the same , and python_lsp is different. 

Do you calculate hash?
![image](https://github.com/ZSaberLv0/ZFVimDirDiff/assets/72234965/157c76c4-30b5-4bd0-99b6-a69c6d2b5d82)

**Comment by ZSaberLv0** [comment]
please supply job log according to this:
https://github.com/ZSaberLv0/ZFVimJob?tab=readme-ov-file#verbose-log

**Comment by eyalk11** [comment]
Thanks. At this point and since you are probably not using hash I prefer to use DiffDirs . 
If you implement ignore line endings difference, I will try again. This is mostly part of the reason it showed mismatch.

**Comment by ZSaberLv0** [comment]
https://github.com/ZSaberLv0/ZFVimDirDiff/commit/b8ab7143ae0137103ea0ddc2699b053217a18f49
added an option `let g:ZFDirDiff_ignoreSpace=0`, set it to 1 and check whether it's what you want?

**Comment by eyalk11** [comment]
Everything works. Thanks!  PS. It is kind of strange as the problem was line endings in linux vs windows and not spaces.
