### ISSUE TITLE
job_TimerCallback issue

### ISSUE THREAD

**Issue by uthpalaherath** [ZSaberLv0/ZFVimDirDiff#43]
Dear developer, 

First of all thanks for this great plugin!
It works well on my Mac, but on an Ubuntu 22 LTS and CentOS 7 systems, with vim versions 8.2 and 9.0, I get the following error when the diff is initiated:

```
Error detected while processing function <SNR>77_jobTimerCallback[5]..ZFJobFuncCall[15]..ZFDirDiffAPI_dataChangedDelayCallback[2]..ZFDirDiffAPI_dataChangedImmediately[23]..<SNR>64_dataChanged_cursorStateRestore:
line   11:
E33: No previous substitute regular expression
```

Would you know what could be going on? I am happy to provide more information if it helps. 

Cheers!
Uthpala

**Comment by ZSaberLv0** [comment]
possibly this: https://github.com/ZSaberLv0/ZFVimDirDiff/commit/353cc659e614681b511ba4cf08e74e3f2b06dafb
update and try again?

**Comment by uthpalaherath** [comment]
Wow that fixed it!
Thank you so much!
