### ISSUE TITLE
Windows下可以不跳出cmd.exe 吗？

### ISSUE THREAD

**Issue by tzws** [ZSaberLv0/ZFVimDirDiff#5]
比如，可以用 call xolox#misc#os#exec({'command': 'vimrun', 'async': 1}) 
这样的东西来控制在后台做对比吗？或者最新的job能做这样的事情吗？

**Comment by ZSaberLv0** [comment]
emmm... 虽然也能做不过改动比较大, 而且感觉 diff 工具做异步好像没太大必要 (好吧主要就是懒, 有很多人觉得有必要的话再看看要不要加吧)

**Comment by ZSaberLv0** [comment]
https://github.com/ZSaberLv0/ZFVimDirDiff/commit/7610fc4a42f3dbc012c772e633b80eecd48a805f
已添加了全异步的实现, 有兴趣可以试试
