### ISSUE TITLE
在对比文件的时候，能把当前对比的两行代码的内容在一个新的窗口显示吗？

### ISSUE THREAD

**Issue by tzws** [ZSaberLv0/ZFVimDirDiff#6]
类似在Beyond Compare那样

![image](https://user-images.githubusercontent.com/23232136/76140619-6e97ed00-6097-11ea-94f5-6814a646ba23.png)

**Comment by ZSaberLv0** [comment]
这个用的是 vim 内置的 diff, 不打算做额外处理

你需要做什么特殊定制的话, 可以 `autocmd User ZFDirDiff_FileEnter xxx`
