### ISSUE TITLE
可以指定比较的文件吗？

### ISSUE THREAD

**Issue by tzws** [ZSaberLv0/ZFVimDirDiff#7]
类在Beyond Compare里，选中两个文件，然后在新的tab页打开，比较内容。
![image](https://user-images.githubusercontent.com/23232136/76140781-d1d64f00-6098-11ea-9d4f-2855f26eca2b.png)

**Comment by ZSaberLv0** [comment]
这个也一直有在考虑, 后面有空会加一下
