### ISSUE TITLE
Dummy file/folder 当比较两个文件夹的时候

### ISSUE THREAD

**Issue by tzws** [ZSaberLv0/ZFVimDirDiff#8]
当比较两个文件夹的时候，某一侧的对应的文件/文件夹不存在，是不是可以用一个 Dummy 的 file/folder来代表一下呢？这样设置折叠为 indent 的时候 就可以两边折叠出的效果一样了。不一样的文件较多的时候，两边分别一折叠，显示就乱了。
这是一边折叠，一边不折叠的时候
![image](https://user-images.githubusercontent.com/23232136/76198818-b3538d80-6229-11ea-9bcf-77939ae4539d.png)

这是两边都折叠的时候。和前期项目比较，前期的项目少了一些文件，所以显示的很乱。
![image](https://user-images.githubusercontent.com/23232136/76198517-30323780-6229-11ea-82a3-aa2b63507aa2.png)

**Comment by ZSaberLv0** [comment]
这个打算用 #4 的方式, 不用 fold 来搞, 大致会做成和 NERDTree 类似的操作习惯, 可以打开和关闭父文件夹, 后续有空弄一下
