### ISSUE TITLE
一侧有文件，另一侧没有文件，打不开

### ISSUE THREAD

**Issue by tzws** [ZSaberLv0/ZFVimDirDiff#9]
在最下方显示 cannot be compared.

![image](https://user-images.githubusercontent.com/23232136/76199252-7e940600-622a-11ea-86ea-cbe0c12b96ed.png)

这个error message 在 messages 里也没有。是不是应该也放到 vim 的messages 里呢？

**Comment by ZSaberLv0** [comment]
这个不打算处理, 感觉没啥必要
